import fs from "fs";
import path from "path";
import Handlebars from "handlebars";
import HtmlToDocx from "@turbodocx/html-to-docx";

/**
 * Register Handlebars Helpers
 */
Handlebars.registerHelper("eq", function (a: any, b: any) {
    return a === b;
});

Handlebars.registerHelper("neq", function (a: any, b: any) {
    return a !== b;
});

Handlebars.registerHelper("gt", function (a: any, b: any) {
    return a > b;
});

Handlebars.registerHelper("lt", function (a: any, b: any) {
    return a < b;
});

/**
 * Helper function to convert various buffer types to Node.js Buffer
 */
function convertToBuffer(data: ArrayBuffer | Blob | Buffer | any): Buffer {
    if (Buffer.isBuffer(data)) {
        return data;
    }

    if (data instanceof ArrayBuffer) {
        return Buffer.from(data);
    }

    if (data instanceof Blob) {
        throw new Error("Blob conversion requires async handling - use convertToBlobAsync");
    }

    if (data && typeof data.buffer !== "undefined") {
        return Buffer.from(data.buffer, data.byteOffset, data.byteLength);
    }

    return Buffer.from(data);
}

/**
 * Helper function to convert Blob to Buffer (async)
 */
async function convertBlobToBuffer(blob: Blob): Promise<Buffer> {
    const arrayBuffer = await blob.arrayBuffer();
    return Buffer.from(arrayBuffer);
}

export async function generateDOCX(
    reportData: Record<string, any>,
    templateName: string
): Promise<Buffer> {
    try {
        const templateFile =
            templateName === "taxEstimation"
                ? "TaxEstimationReportTemplate.hbs"
                : "TransactionReportTemplete.hbs";

        const templatePath = path.join(__dirname, "../hbs", templateFile);

        if (!fs.existsSync(templatePath)) {
            throw new Error(`Template not found: ${templatePath}`);
        }

        const templateContent = fs.readFileSync(templatePath, "utf-8");
        const compiledTemplate = Handlebars.compile(templateContent);

        const enhancedData = {
            ...reportData,
            generatedOn:
                reportData.generatedOn ||
                new Date().toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                }),
        };

        const html = compiledTemplate(enhancedData);

        const docxOptions = {
            orientation: "portrait" as const,
            format: "A4" as const,
            margins: {
                top: 1440,
                right: 1440,
                bottom: 1440,
                left: 1440,
            },
            title: templateName === "taxEstimation" ? "Tax Estimation Report" : "Transaction Report",
            subject: "Professional Financial Report",
            creator: "TaxPal Professional Services",
            keywords: ["tax", "financial", "professional", "report"],
            description: "Professional tax estimation report generated by TaxPal",
            font: "Calibri",
            fontSize: 24,
            lineHeight: 1.5,
            company: "TaxPal",
            category: "Financial Reports",
        };

        const docxResult = await HtmlToDocx(html, null, docxOptions);

        let docxBuffer: Buffer;
        if (docxResult instanceof Blob) {
            docxBuffer = await convertBlobToBuffer(docxResult);
        } else {
            docxBuffer = convertToBuffer(docxResult);
        }

        return docxBuffer;
    } catch (err) {
        console.error("❌ Error generating professional DOCX:", err);
        throw new Error(`Failed to generate professional DOCX: ${(err as Error).message}`);
    }
}